### ISSUE TITLE
Question: How to instrument an arbitrary function?

### ISSUE THREAD

**Issue by steviee** [xing/logjam-agent-go#12]
Currently, we use a net/http (or compatible) middleware to wrap function calls to http handlers and log the handlerfunc. 

I wonder how I could wrap just any func() to have it in logjam. This would be especially useful for monitoring non-http triggered calls like gRPC, or subscribers to Kafka or NATS/AMQP, ...

Is this somehow possible?

**Comment by skaes** [comment]
I believe this question is now answered by the README
